### ISSUE TITLE
No longer support DB CA cert as parameter with its content

### ISSUE THREAD

**Issue by HDYA** [cloudfoundry/azurefilebroker#1]
[#af7e7de](https://github.com/cloudfoundry/azurefilebroker/commit/af7e7dea56120a309e1fcee1fd556ace9fab49b5#diff-7ddfb3e035b42cd70649cc33393fe32c)
Changes to "cert path" will make it hard to configure the cert from PCF Ops Manager.

Should at least support both.

**Comment by mariash** [comment]
@HDYA we fixed an issue with database cert for `azurefilebroker` job. In future though we would recommend switching to `azurefilebrokerpush` errand that deploys broker as a CF app instead of running it as a BOSH job. This will save VM and it is a standard way of how we are deploying it nowadays.

**Comment by julian-hj** [comment]
Note that the fix for this issue is in https://github.com/cloudfoundry/smb-volume-release/tree/master/jobs/azurefilebroker/templates even though the issue is posted here.

**Comment by HDYA** [comment]
Thanks Julian and Maria, we'll publish new version of tiles soon so I kind of considering work on the same fix earlier

**Comment by HDYA** [comment]
Hi @mariash and @julian-hj 
Sorry to bother you guys again, I came across the issue again and found I forgot to mention that our tile for SMB Volume Service actually treat the file broker as a service broker application from the very beginning.
While I'm still confused why we need to write the cert content into local file system, since it is actually more unsecure than environment variable? Do we have a issue involving content misrepresentation when in environment variable or is this a change for CredHub or something else? 
Thanks

**Comment by julian-hj** [comment]
@HYDA writing the cert into the file system was the only way we could get the cert to work while passing it through the bosh errand to the cf cli to push it.  It's possible that there was some way to make it work with multiply escaped strings, but we did not find a character encoding that would allow a multiline string to pass from the bosh manifest through the errand process into the cli, and finally into the running application without losing the line breaks.

Regarding the question of security, the certificate in question is the public ca cert for the database server, so it would not afford an attacker any extra access to the that they don't get by simply skipping server certificate validation.

HTH,
-Julian
